# Generated by Django 4.0.2 on 2022-08-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
